### ISSUE TITLE
storage location 

### ISSUE THREAD

**Issue by evelynmitchell** [amirrezasalimi/note#1]
You don't explain where the note is stored, If it is local storage, you should mention that.

If it is stored on a central server, that would be good to mention.

**Comment by amirrezasalimi** [comment]
Thanks for feedback @evelynmitchell  
I am going to explain that in readme file soon

**Comment by amirrezasalimi** [comment]
updated readme

**Comment by evelynmitchell** [comment]
Thanks for explaining this!
